name: sieves_mob
description: "Sieves Mobile"

publish_to: 'none'

version: 1.26.0+33

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.2
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.1
  equatable: ^2.0.5
  freezed: ^3.2.3
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  flutter_web_auth_2: ^4.1.0
  flutter_secure_storage: ^9.2.4
  iconsax: ^0.0.8
  http: ^1.1.0
  auth0_flutter: ^1.7.2
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3
  firebase_messaging: ^15.1.3
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^28.1.33
  image_picker: ^1.0.7
  camera: ^0.11.0+2
  path_provider: ^2.1.2
  geolocator: ^13.0.2
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/presentations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
